"""feat: init schema

Revision ID: 136cb8b0581d
Revises: 
Create Date: 2025-12-27 12:43:58.152177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136cb8b0581d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=350), nullable=False),
    sa.Column('clean_name', sa.String(length=256), nullable=False),
    sa.Column('level', sa.Enum('BACHELOR', 'SPECIALIST', 'MASTER', 'RESIDENCY', name='educationlevel'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_specialities_code'), 'specialities', ['code'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('course_number', sa.SmallInteger(), nullable=False),
    sa.Column('stream', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('speciality_id', 'course_number', 'stream', 'name', name='uq_groups_identity')
    )
    op.create_index('idx_groups_structure', 'groups', ['speciality_id', 'course_number', 'stream'], unique=False)
    op.create_table('subgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'name', name='uq_subgroups_group_name')
    )
    op.create_table('lessons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('lesson_type', sa.Enum('LECTURE', 'SEMINAR', name='lessontype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('teacher', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subgroup_id', 'date', 'start_time', 'subject', name='uq_lesson_unique')
    )
    op.create_index('idx_lessons_lookup', 'lessons', ['subgroup_id', 'date'], unique=False)
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('notification_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('idx_lessons_lookup', table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('subgroups')
    op.drop_index('idx_groups_structure', table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_specialities_code'), table_name='specialities')
    op.drop_table('specialities')
    # ### end Alembic commands ###
